## To modify by developper(s) of the plugin

[plugin-info]
SHORT_PLUGIN_NAME = 'rohdeschwarz' 

package-url = 'https://github.com/PyMoDAQ/pymodaq_plugins_rohdeschwarz' #to modify
description = 'PyMoDAQ plugins for instruments from Rohde & Schwarz, only SMA/SMB microwave sources so far.'

author = 'Aurore Finco'
author-email = 'aurore.finco@umontpellier.fr'
license = 'MIT'

[plugin-install]
#packages required for your plugin:
packages-required = ['pymodaq>=4.0.0']
